export const scenarios = {
  playground: {
    name: "Playground",
    config: {
      bgColor: 0,
      textColor: 1,
      textColorHover: 255,
      radius: 300,
      strength: 1,
      boldness: 900,
      lineHeight: 0.9,
      textDelimiter: " ",
      animationSpeed: 10,
      fontSize: 128,
      wordGap: 0,
      fontFamily: "Bitter",
    },
    lines: [
      "ALPHA BRAVO CHARLIE DELTA ECHO",
      "FOXTROT GOLF HOTEL INDIA JULIET",
      "KILO LIMA MIKE NOVEMBER OSCAR PAPA",
      "QUEBEC ROMEO SIERRA TANGO UNIFORM",
      "VICTOR WHISKEY XRAY YANKEE ZULU",
    ],
    layout: "center",
    animate: true,
  },
  juicyHeader: {
    name: "Juicy Header",
    config: {
      bgColor: 255,
      textColor: 192,
      textColorHover: 0,
      radius: 200,
      strength: 1.5,
      boldness: 900,
      lineHeight: 1,
      textDelimiter: "",
      animationSpeed: 0,
      fontSize: 72,
      wordGap: 128,
      fontFamily: "Montserrat",
    },
    words: ["WORK", "ABOUT", "NEWS", "STORE", "CONTACT"],
    layout: "top",
    animate: false,
  },
  pastime: {
    name: "Pastime",
    config: {
      bgColor: 30,
      textColor: 60,
      textColorHover: 255,
      radius: 200,
      strength: 1,
      boldness: 900,
      lineHeight: 1,
      textDelimiter: " • ",
      animationSpeed: 2,
      fontSize: 48,
      wordGap: 0,
      fontFamily: "Roboto",
    },
    teams: [
      {
        name: "Diamondbacks",
        color: "#A71930",
        logo: "/src/assets/logos/diamondbacks.svg",
        players: [
          "PERDOMO",
          "MARTE",
          "CARROLL",
          "MORENO",
          "ARENADO",
          "SANTANA",
          "DEL CASTILLO",
          "LAWLAR",
          "THOMAS",
        ],
      },
      {
        name: "Rockies",
        color: "#33006F",
        logo: "/src/assets/logos/rockies.svg",
        players: [
          "TOVAR",
          "MONIAK",
          "GOODMAN",
          "BECK",
          "JOHNSTON",
          "DOYLE",
          "CASTRO",
          "MCCARTHY",
          "JULIEN",
        ],
      },
      {
        name: "Dodgers",
        color: "#005A9C",
        logo: "/src/assets/logos/dodgers.svg",
        players: [
          "OHTANI",
          "TUCKER",
          "BETTS",
          "FREEMAN",
          "SMITH",
          "MUNCY",
          "HERNÁNDEZ",
          "PAGES",
          "EDMAN",
        ],
      },
      {
        name: "Padres",
        color: "#2F241D",
        logo: "/src/assets/logos/padres.svg",
        players: [
          "BOGAERTS",
          "MERRILL",
          "MACHADO",
          "TATIS JR",
          "CRONENWORTH",
          "LAUREANO",
          "SHEETS",
          "ANDUJAR",
          "FERMIN",
        ],
      },
      {
        name: "Giants",
        color: "#FD5A1E",
        logo: "/src/assets/logos/giants.svg",
        players: [
          "ARRAEZ",
          "BADER",
          "ADAMES",
          "DEVERS",
          "CHAPMAN",
          "RAMOS",
          "ELDRIDGE",
          "LEE",
          "BAILEY",
        ],
      },
    ],
    layout: "center",
    animate: true,
  },
};

export const defaultScenario = "playground";
