export const scenarios = {
  playground: {
    name: "Playground",
    config: {
      bgColor: 0,
      textColor: 4,
      textColorHover: 255,
      radius: 300,
      strength: 1,
      boldness: 900,
      lineHeight: 0.9,
      textDelimiter: " ",
      animationSpeed: 10,
      fontSize: 128,
      wordGap: 0,
      fontFamily: "Bitter",
    },
    lines: [
      "ALPHA BRAVO CHARLIE DELTA ECHO",
      "FOXTROT GOLF HOTEL INDIA JULIET",
      "KILO LIMA MIKE NOVEMBER OSCAR PAPA",
      "QUEBEC ROMEO SIERRA TANGO UNIFORM",
      "VICTOR WHISKEY XRAY YANKEE ZULU",
    ],
    layout: "center",
    animate: true,
  },
  juicyHeader: {
    name: "Juicy Header",
    config: {
      bgColor: 255,
      textColor: 192,
      textColorHover: 0,
      radius: 200,
      strength: 1.5,
      boldness: 900,
      lineHeight: 1,
      textDelimiter: "",
      animationSpeed: 0,
      fontSize: 72,
      wordGap: 128,
      fontFamily: "Montserrat",
    },
    words: ["WORK", "ABOUT", "NEWS", "STORE", "CONTACT"],
    layout: "top",
    animate: false,
  },
};

export const defaultScenario = "playground";
